### ISSUE TITLE
K1c - build volume

### ISSUE THREAD

**Issue by Wannebet** [tlace17/K1-Linear-Rail-Gantry#5]
Hi, i've done this project on my k1c.
However it seems that i've lost some build volume in the back of the printer. 
The nozzle can not reach the wiping brush anymore.
![Uploading 20240819_144347.jpg…]()
![Uploading 20240819_144249.jpg…]()
Anything i did wrong?

**Comment by tlace17** [comment]
This is normal and stated in the documentation that you lose a bit of build area, just move the brush up the the absolute back your toolhead can go and change build area in slicer appropriately.

**Comment by Wannebet** [comment]
Hi, okay! Perfect i thought i did something wrong.
Thank you for the quick reply.
