### ISSUE TITLE
Y-axis linear rails

### ISSUE THREAD

**Issue by amr-labib** [tlace17/K1-Linear-Rail-Gantry#6]
Hi,

Are there any plans for a version with Y-axis Linear rails?

Thanks,
Labib

**Comment by ACKET2009** [comment]
The original creality rods is 8mm and they vibrate during the testing of X axis for input shaper... It will be better to place the X rodas to the Y position... IMHO

**Comment by tlace17** [comment]
Linear Rails on Y were trials for over 4 months and due to the flexible nature of the creality frame they cause large racking issues and binding, therefore the work was scrapped.

**Comment by ACKET2009** [comment]
I find this source https://github.com/kemsky/creality-k1-max-xy-rails-mod maybe it will help...

**Comment by tlace17** [comment]
> I find this source https://github.com/kemsky/creality-k1-max-xy-rails-mod maybe it will help...

This requires modification of the K1 frame, this is something that is beyond the scope of what I was trying to accomplish. This mod was intended to be accessible to people without physical modification to any part of your printer.
