### ISSUE TITLE
The XY joints 

### ISSUE THREAD

**Issue by ACKET2009** [tlace17/K1-Linear-Rail-Gantry#8]
the parts with slots are backlash on the bearings, please, could you add the parts with holes for a linear bearing without a slots?

**Comment by tlace17** [comment]
I have a version I can upload, but with proper printer tolerance they should be an extremely tight fit

**Comment by ACKET2009** [comment]
> I have a version I can upload, but with proper printer tolerance they should be an extremely tight fit

Yes! Place it, please!

**Comment by ACKET2009** [comment]
Or, may be, if it is not difficult, You can send it by e-mail to A.ASverdlov@gmail.com...
